sudo: required
language: bash
install:
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Travis-CI"

  - mkdir -p ~/my-nix
  - sudo mkdir -p /nix
  - sudo chown $USER /nix
  - sudo cp -r ~/my-nix /nix

  - sudo mkdir -p /nix/store
  - sudo chown -R $USER /nix
  - ls /nix/store | wc
  - ls -l /nix/store
        
  - curl https://nixos.org/nix/install | sh  
  - . ~/.nix-profile/etc/profile.d/nix.sh

  - ls /nix/store | wc
  - ls -l /nix/store

  - nix-shell -p hello --command hello

  - ls /nix/store | wc
  - ls -l /nix/store

  - cp -r /nix ~/my-nix
  #- ./try-reflex --command "exit 0"
  #- travis_wait ./test -j 2
cache:
  directories:
    - ~/my-nix
os:
  - linux
  - osx


