sudo: required
language: bash
install:  
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Travis-CI"

  - sudo mkdir -p /nix
  - sudo chown $USER /nix
  - curl https://nixos.org/nix/install | sh  
  - . ~/.nix-profile/etc/profile.d/nix.sh
      
  - nix-shell -p hello --command hello
  #- ./try-reflex --command "exit 0"
  #- travis_wait ./test -j 2
cache:
  directories:
    - /nix
os:
  - linux
  - osx


