version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      
      - run: df -h
      - run: git config --global user.email "travis-ci@example.com"
      - run: git config --global user.name "Travis-CI"

      - run: sudo mkdir -p /nix
      - run: sudo chown $USER /nix
      
      - restore_cache:
          keys:
            - reflex

      - run: df -h
      - run: curl https://nixos.org/nix/install | sh
      - run: ./try-reflex --command "exit 0"

      - run: df -h          

      - run: nix-collect-garbage
      - run: df -h
      - run: ./test -j 2
      - run: df -h        
      - save_cache:
          key: reflex-{{ epoch }}
          paths: /nix





