version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      - run: curl https://nixos.org/nix/install | sh

      - restore_cache:
          keys:
            - my-cache
        
      - run: nix-shell -p hello --command hello

      - save_cache:
          key: my-cache
          paths: /nix/store

