version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"

    docker:
      - image: nixos/nix

    steps:
#      - run: sudo mkdir -p /nix

#      - restore_cache:
#          keys:
#            - my-nix

#      - run: chown $USER /nix


      - run: ls -ld /
      - run: chmod go-w /
      - run: ls -ld /
      - run: nix-env -i git        
      - run: git config --global user.email "travis-ci@example.com"
      - run: git config --global user.name "Travis-CI"

      - checkout
#      - run: curl https://nixos.org/nix/install | sh
      - run: ./try-reflex --command "exit 0"
      - run: ./test -j 2
        
      - save_cache:
          key: my-nix-{{ epoch }}
          paths: /nix



