version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout

      - run: sudo mkdir -p /nix
      - run: sudo chown circleci /nix
      
      - restore_cache:
          keys:
            - my-nix

      - run: curl https://nixos.org/nix/install | sh
        
      - run: ls /nix/store | wc
      - run: ls -l /nix/store

      - run: nix-shell -p hello --command hello

      - run: ls /nix/store | wc
      - run: ls -l /nix/store
        
      - save_cache:
          key: my-nix
          paths: /nix



