version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      #- run: echo $PATH
      - run: curl https://nixos.org/nix/install | sh
      #- run: cat ~/.nix-profile/etc/profile.d/nix.sh
      #- run: echo $PATH
      #- run: . /home/circleci/.nix-profile/etc/profile.d/nix.sh
      # - run: source ~/.nix-profile/etc/profile.d/nix.sh # doesn't work for some reason
      - run: nix-env
      #- run: nix-shell -p hello --command hello

