version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      
      - run: mkdir -p ~/nix-store
      - restore_cache:
          keys:
            - my-proxy-cache
      - run: sudo mkdir -p /nix
      - run: sudo chown -R circleci /nix
      - run: sudo mv ~/nix-store /nix/store

      - run: ls /nix/store
      - run: curl https://nixos.org/nix/install | sh
      - run: ls /nix/store
        
      - run: nix-shell -p hello --command hello

      - run: cp -r /nix/store ~/nix-store
    
      - save_cache:
          key: my-proxy-cache
          paths: ~/nix-store

#
