version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      - run: curl https://nixos.org/nix/install | sh
      - run: nix-shell -p hello --command hello

