version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run: curl https://nixos.org/nix/install | sh
      - run: cat ~/.nix-profile/etc/profile.d/nix.sh
      - run: echo $PATH
      - run: source ~/.nix-profile/etc/profile.d/nix.sh
      - run: echo $PATH
      - run: nix-env
      #- run: nix-shell -p hello --command hello

