version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - my-dump

      - run: curl https://nixos.org/nix/install | sh

      - run: if [ -f "~/dump"]; then nix-store --restore ~/dump; fi;

      - run: ls /nix/store | wc
      - run: ls -l /nix/store

      - run: nix-shell -p hello --command hello

      - run: ls /nix/store | wc
      - run: ls -l /nix/store

      - run: nix-store /nix/store ~/dump
        
      - save_cache:
          key: my-dump
          paths: ~/dump



