version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - my-dump3

      - run: curl https://nixos.org/nix/install | sh

      - run: ls ~
      - run: if [ -f "$HOME/dump" ]; then nix-store --import ~/dump; else echo "bah"; fi;
        
      - run: ls /nix/store | wc
      - run: ls -l /nix/store

      - run: nix-shell -p hello --command hello

      - run: ls /nix/store | wc
      - run: ls -l /nix/store

      - run: nix-store --export /nix/store > ~/dump
        
      - save_cache:
          key: my-dump3
          paths: ~/dump



