version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"

    docker:
      - image: nixos/nix

    steps:
      - checkout

      - run: apk update && apk upgrade && apk add git
      - run: git config --global user.email "travis-ci@example.com"
      - run: git config --global user.name "Travis-CI"

#      - run: sudo mkdir -p /nix
#      - run: sudo chown $USER /nix
      
      - restore_cache:
          keys:
            - my-nix

      - run: curl https://nixos.org/nix/install | sh
      - run: ./try-reflex --command "exit 0"
      - run: ./test -j 2
        
      - save_cache:
          key: my-nix-{{ epoch }}
          paths: /nix



