version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout

      - run: sudo mkdir -p /nix
      - run: sudo chown $USER /nix
      
      - restore_cache:
          keys:
            - my-nix

      - run: curl https://nixos.org/nix/install | sh
      - run: ./try-reflex --command "exit 0"
      - run: travis_wait ./test -j 2
        
      - save_cache:
          key: my-nix-{{ epoch }}
          paths: /nix



